### PR TITLE
Parser v2

### PR DESCRIPTION
**Pull request by MaximeAlgosup**
Version: 0.0.5

Description:

Rework the whole program because the previous design was wrong

This version does not contain:
- Builder
- Bin exporter

This version contains:
- New version of the parser
- Simpler and much efficient data structure
- Improved error system

### CODE REVIEW

**Review by EnzoGuillouche — APPROVED** [review]
Everything seems alright. At least the wrong parts are changed. Merging approved.

**Review by MathiasGagnepain — APPROVED** [review]
everything seems ok

**Comment by EnzoGuillouche** [comment]
We need to merge the branch when the server is available, because the runner requires a password for now.

**Comment by MathiasGagnepain** [comment]
PR close Issue with github action (@Jippay issue)

**Pull request closed without merging**
